### PR TITLE
Add PebblesDB compatibility and ability to run with YCSB benchmarks

### PR DESCRIPTION
**Pull request by abhijith97**
Implemented a Java JNI Wrapper so that Java applications can access PebblesDB. Since PebblesDB is API compatible with LevelDB, LevelDBJNI codebase was leveraged to do the task. 

- Only minor changes are required in the pebblesDB codebase. As of now, the changes are packaged as a patch in the current project. If the patch seems fine to merge with pebblesDB, it can be removed from here. 
- Removed support for **Suspend/Resume compaction** from the original code as it is not implemented in pebblesDB.
- Currently, the fork of YCSB under utsaslab forked locally by me has the bindings for pebblesDB. As a result the instructions for running YCSB points to that repository. Once that is merged, the readme should be edited.
- A setup script does the job of copying and editing the pebblesDB build files to make it compatible with the leveldbjni.  
- Readme is updated for the use case and includes instructions for running it with YCSB. 
- Updated the repository to support the latest version of dependencies.

## Tests

- There are no behavioral changes to pebblesDB. `db_test` **PASSES** after the patch.
- Test suite in this project gets a score of (18/20). **One test is related to suspend/resume. The other is related to the internal structure of storage and is specific to levelDB. As a result, they are removed from the test suite.** 
- YCSB benchmarks run over this wrapper returns **"OK"** for all transactions.

### CODE REVIEW

File: leveldbjni-linux64-aarch64/pom.xml [hunk 1]
```diff
@@ -64,7 +64,7 @@
       </plugin>
       <plugin>
         <groupId>org.fusesource.hawtjni</groupId>
-        <artifactId>maven-hawtjni-plugin</artifactId>
+        <artifactId>hawtjni-maven-plugin</artifactId>
```
Comment (xxks-kkk) [inline leveldbjni-linux64-aarch64/pom.xml:67]: Just curious why the change to the `pom.xml` here?

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java [hunk 2]
```diff
@@ -219,59 +219,15 @@ public void suspendCompactions() throws InterruptedException {
         if( db==null ) {
             throw new DBException("Closed");
         }
-        db.suspendCompactions();
+	// Not implemented
```
Comment (xxks-kkk) [inline leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java]: Can you add your github id in parentheses and describe why you comment out the code here?

```
// (github id) To fix issue https://github.com/utsaslab/pebblesdb/issues/2, ... (briefly describe your reasoning here)
```

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java [hunk 3]
```diff
@@ -219,59 +219,15 @@ public void suspendCompactions() throws InterruptedException {
...
+        // db.suspendCompactions();
     }
+
     public void resumeCompactions() {
         if( db==null ) {
             throw new DBException("Closed");
         }
-        db.resumeCompactions();
+	// Not implemented
+        // db.resumeCompactions();
```
Comment (xxks-kkk) [inline leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java:243]: Same comment as above

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java [hunk 4]
```diff
@@ -219,59 +219,15 @@ public void suspendCompactions() throws InterruptedException {
...
     }
-
```
Comment (xxks-kkk) [inline leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java]: For the code change here, if we don't invoke the functions below, do we still need to comment them out?

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/NativeDB.java [hunk 5]
```diff
@@ -162,12 +162,6 @@ static final native void CompactRange(
                 @JniArg(flags={NO_OUT}) NativeSlice begin,
                 @JniArg(flags={NO_OUT}) NativeSlice end
                 );
-
```
Comment (xxks-kkk) [inline leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/NativeDB.java:165]: I'm not sure if we need to comment out below methods. The idea is that we want to keep the changes to minimal.

File: leveldbjni/src/main/native-package/Makefile.in [hunk 6]
```diff
@@ -300,6 +300,7 @@ LIBTOOL = @LIBTOOL@
 LIPO = @LIPO@
 LN_S = @LN_S@
 LTLIBOBJS = @LTLIBOBJS@
+LT_SYS_LIBRARY_PATH = @LT_SYS_LIBRARY_PATH@
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/Makefile.in]: Can you explain what's the purpose of this change?

File: leveldbjni/src/main/native-package/Makefile.in [hunk 7]
```diff
@@ -368,6 +369,7 @@ pdfdir = @pdfdir@
 prefix = @prefix@
 program_transform_name = @program_transform_name@
 psdir = @psdir@
+runstatedir = @runstatedir@
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/Makefile.in]: Can you explain what's the purpose of this change?

File: leveldbjni/src/main/native-package/autotools/ltmain.sh [hunk 8]
```diff
@@ -1,9 +1,12 @@
+#! /bin/sh
+## DO NOT EDIT - This file generated from ./build-aux/ltmain.in
+##               by inline-source v2014-01-03.01
 
-# libtool (GNU libtool) 2.4.2
+# libtool (GNU libtool) 2.4.6
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/autotools/ltmain.sh]: I don't think we need to check in this code change since this is automatically generated?

File: leveldbjni/src/main/native-package/configure [hunk 9]
```diff
@@ -662,6 +662,7 @@ JNI_EXTRA_CFLAGS
 JNI_JDK
 CXXCPP
 CPP
+LT_SYS_LIBRARY_PATH
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/configure]: Do we need to include the change to this file? Is it automatically generated from autotool?

File: leveldbjni/src/main/native-package/configure.ac [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+# ---------------------------------------------------------------------------
+
+## --------------------------------
+## Initialization macros.
+## --------------------------------
+AC_PREREQ([2.61])
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/configure.ac]: Could you explain why we need to add this file to the repo?

File: leveldbjni/src/main/native-package/m4/libtool.m4 [hunk 11]
```diff
@@ -1,45 +1,37 @@
 # libtool.m4 - Configure libtool for the host system. -*-Autoconf-*-
 #
-#   Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2003, 2004, 2005,
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/m4/libtool.m4]: I'm amazed to see the amount of changes you made to the `libtool.m4`. I'm wondering why those changes are related to our goal?

File: leveldbjni/src/main/native-package/m4/ltoptions.m4 [hunk 12]
```diff
@@ -1,14 +1,14 @@
 # Helper functions for option handling.                    -*- Autoconf -*-
 #
-#   Copyright (C) 2004, 2005, 2007, 2008, 2009 Free Software Foundation,
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/m4/ltoptions.m4]: Why changes to the comment header? Are those changes automatically generated somehow? If so, can you not include those automatically generated files in your pull request?

File: leveldbjni/src/main/native-package/src/config.h.in [hunk 13]
```diff
@@ -36,8 +36,7 @@
 /* Define to 1 if you have the <unistd.h> header file. */
 #undef HAVE_UNISTD_H
 
-/* Define to the sub-directory in which libtool stores uninstalled libraries.
-   */
+/* Define to the sub-directory where libtool stores uninstalled libraries. */
```
Comment (xxks-kkk) [inline leveldbjni/src/main/native-package/src/config.h.in]: I don't think we need this change?

File: pebblesdb.patch [hunk 14]
```diff
@@ -0,0 +1,33 @@
+diff --git a/CMakeLists.txt b/CMakeLists.txt
+index 8f0f1c3..55af696 100644
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -142,6 +142,9 @@ target_sources(pebblesdb
```
Comment (xxks-kkk) [inline pebblesdb.patch:5]: I'm wondering what's this file for this pull request? If the patch is for PebblesDB, can you make a pull request to the PebblesDB repo?

File: pom.xml [hunk 15]
```diff
@@ -51,7 +51,7 @@
     <forge-project-id>leveldbjni</forge-project-id>
     <forge-project-id-uc>LEVELDBJNI</forge-project-id-uc>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <hawtjni-version>1.11</hawtjni-version>
```
Comment (xxks-kkk) [inline pom.xml:54]: The version number change is critical to your implementation?

**Review by xxks-kkk — CHANGES_REQUESTED** [review]
Hello @abhijith97 ,

Thanks for the pull request and effort to the feature. Can you help to address the comments I write for your changes?

I haven't run your code yet but I think I can follow your README guide? If so, I'll try my best to do it soon.

Thanks!

File: leveldbjni-linux64-aarch64/pom.xml (hunk 1 above)
Comment (abhijith97) [reply leveldbjni-linux64-aarch64/pom.xml:67]: The artifactId was changed in the 1.16 version of hawtjni. Since I updated it from 1.11, this ID had to be changed.

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java (hunk 4 above)
Comment (abhijith97) [reply leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java]: Those are already commented out code in the original codebase, I deleted them since we do not have support for resume/suspend compactions. Should the comments be retained?

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/NativeDB.java (hunk 5 above)
Comment (abhijith97) [reply leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/NativeDB.java:165]: These annotated methods are used by hawtjni to create the mapping. Since these are not implemented by the C++ codebase, hawtjni errors would be produced.
`[INFO] src/leveldbjni.cpp:426:35: error: 'class leveldb::DB' has no member named 'ResumeCompactions'
[INFO]   ((leveldb::DB *)(intptr_t)arg0)->ResumeCompactions();
`

File: leveldbjni/src/main/native-package/configure.ac (hunk 10 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/configure.ac]: Actually, all the changes in `leveldbjni/src/main/native-package` are auto-generated by autotools.  It was incorrectly packed with this pull request. I was fixing a build error caused by version mismatch of automake by using this file. It was an error on my end, the changes in  `leveldbjni/src/main/native-package` are unnecessary and I will remove them.

File: leveldbjni/src/main/native-package/m4/ltoptions.m4 (hunk 12 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/m4/ltoptions.m4]: Yes, they are auto-generated. 
https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: pebblesdb.patch (hunk 14 above)
Comment (abhijith97) [reply pebblesdb.patch:5]: I provided this patch here since these changes in PebblesDB are needed for compatibility to this project.
PebblesDB as such does not benefit from this patch. The original project also contains a similar patch to LevelDB. 
Do you want me to make a pull request to PebblesDB?

File: pom.xml (hunk 15 above)
Comment (abhijith97) [reply pom.xml:54]: It is not critical. The original project was updating this version over time but the project does not seem to have commits of late. 
Changelog for hawtjni : https://github.com/fusesource/hawtjni/blob/master/changelog.md
Do you want me to revert back to the original version?

File: leveldbjni/src/main/native-package/Makefile.in (hunk 7 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/Makefile.in]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/native-package/src/config.h.in (hunk 13 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/src/config.h.in]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/native-package/m4/libtool.m4 (hunk 11 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/m4/libtool.m4]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/native-package/Makefile.in (hunk 6 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/Makefile.in]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/native-package/autotools/ltmain.sh (hunk 8 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/autotools/ltmain.sh]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/native-package/configure (hunk 9 above)
Comment (abhijith97) [reply leveldbjni/src/main/native-package/configure]: https://github.com/utsaslab/leveldbjni/pull/1/files/4ece7fed84bed249e85ecc72d6f4e81d68a883b9#r219715836

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java (hunk 2 above)
Comment (abhijith97) [reply leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java]: Sure, will do this.

File: leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java (hunk 3 above)
Comment (abhijith97) [reply leveldbjni/src/main/java/org/fusesource/leveldbjni/internal/JniDB.java:243]: Sure, will do this.

**Comment by abhijith97** [comment]
I have made a pull request for the pebblesDB bindings here : https://github.com/utsaslab/YCSB/pull/1

File: readme.md [hunk 16]
```diff
@@ -234,19 +190,22 @@ Compile the snappy project.  This produces a static library.
...
+    cmake .. && make install -j16
+
 
 Now use maven to build the leveldbjni project. 
     
     cd ${LEVELDBJNI_HOME}
+    chmod a+x setup.sh
+    ./setup.sh
+    export LEVELDB_HOME=`cd pebblesdb; pwd`
+    autoreconf -i leveldbjni/src/main/native-package
```
Comment (xxks-kkk) [inline readme.md]: Probably add one more step here: `export platform=linux64`?

File: readme.md [hunk 17]
```diff
@@ -203,21 +160,20 @@ See also [releasing.md](releasing.md):
...
- * CentOS 5.6 (32 and 64 bit)
- * Ubuntu 12.04 (32 and 64 bit)
- * apt-get install autoconf libtool
+ * Ubuntu 14.04, 16.06, 18.04 (64 bit)
+ 
+ Run : apt-get install autoconf libtool
 
 ### Build Procedure
 
 Then download the snappy, leveldb, and leveldbjni project source code:
```
Comment (xxks-kkk) [inline readme.md]: Switch "leveldb" to "pebblesdb"

File: readme.md [hunk 18]
```diff
@@ -203,21 +160,20 @@ See also [releasing.md](releasing.md):
...
 
-    wget http://snappy.googlecode.com/files/snappy-1.0.5.tar.gz
+    wget https://src.fedoraproject.org/lookaside/pkgs/snappy/snappy-1.0.5.tar.gz/4c0af044e654f5983f4acbf00d1ac236/snappy-1.0.5.tar.gz
     tar -zxvf snappy-1.0.5.tar.gz
-    git clone git://github.com/chirino/leveldb.git
-    git clone git://github.com/fusesource/leveldbjni.git
+    git clone https://github.com/utsaslab/pebblesdb.git
+    git clone https://github.com/abhijith97/leveldbjni
```
Comment (xxks-kkk) [inline readme.md]: I think this link can be fixed to `utsaslab/levledbjni`?

**Comment by xxks-kkk** [comment]
@abhijith97 Thanks for the work. I have tested locally with your another pull request. Everything works successfully. The only minor point I would suggest is to fix the instruction (e.g. `git clone`) to the repo under utsaslab domain. Other than this, everything looks good to me.

Please squash your changes into one commit and merge. We want to keep the commit history clean :-)

**Comment by vijay03** [comment]
@abhijith97 could you please make the changes requested by @xxks-kkk? Looking forward to getting this merged!

**Comment by abhijith97** [comment]
@vijay03 @xxks-kkk I have made the changes. Could you please tell me if it is good to merge?

**Review by xxks-kkk — APPROVED** [review]
